spring:
  datasource:
    url: jdbc:mysql://metro.proxy.rlwy.net:56456/railway?createDatabaseIfNotExist=true
    username: root
    password: "akkKfiiDEPxRRLBQDSGkqdqVvMtDNVTY"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8090